### ISSUE TITLE
Wrong patch file generated when the attribute has xml namespace

### ISSUE THREAD

**Issue by chucklu** [CameronWills/FatAntelope#7]
I have the following source file and target file
1.source file
```xml 
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <runtime>
    <assemblyBinding>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Extensions" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```
2.target file
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Data.Edm" publicKeyToken="31BF3856AD364E35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.6.4.0" newVersion="5.6.4.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

3.when I generated the patch file,I got this
```xml
<configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1" xdt:Transform="SetAttributes(xmlns)">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Data.Edm" publicKeyToken="31BF3856AD364E35" xdt:Transform="SetAttributes(name,publicKeyToken)" />
        <bindingRedirect oldVersion="0.0.0.0-5.6.4.0" newVersion="5.6.4.0" xdt:Transform="Replace" xmlns="urn:schemas-microsoft-com:asm.v1" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

4.After applying the patch to source file,I got nothing. The base.xml keep the same as before.

**Comment by chucklu** [comment]
Something weird in patch file, the xmlns attribute of assemblyBinding is same in base and target file.
But the patch file contains it. I will try to debug it.

**Comment by chucklu** [comment]
when I  try the following source and target file
1.source file
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Extensions" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```
2.target file
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
	  <dependentAssembly>
        <assemblyIdentity name="System.Web.Extensions" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Data.Edm" publicKeyToken="31BF3856AD364E35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.6.4.0" newVersion="5.6.4.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```
3.patch file
```xml
<configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1" xdt:Transform="SetAttributes(xmlns)">
      <dependentAssembly xdt:Transform="Insert" xmlns="urn:schemas-microsoft-com:asm.v1">
        <assemblyIdentity name="Microsoft.Data.Edm" publicKeyToken="31BF3856AD364E35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.6.4.0" newVersion="5.6.4.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```
4.when I try to apply the patch, the error message I got is:
Microsoft.Web.XmlTransform.XmlNodeException: No element in the source document matches '/configuration/runtime/_defaultNamespace:assemblyBinding/_defaultNamespace:dependentAssembly'
   at Microsoft.Web.XmlTransform.XmlTransformationLogger.LogErrorFromException(Exception ex)
   at Microsoft.Web.XmlTransform.XmlTransformation.Apply(XmlDocument xmlTarget)
   at Chuck.Test.ChuckTest.DiffTest() in E:\GitHub\Other\FatAntelope\Chuck.Test\ChuckTest.cs:line 59
